INSERT INTO MutualFundDetails VALUES ('HINDUSTAN',135.84);
INSERT INTO MutualFundDetails VALUES ('ADANI',100.14);
INSERT INTO MutualFundDetails VALUES ('SBI',104.14);
INSERT INTO MutualFundDetails VALUES ('ONGC',835.84);
INSERT INTO MutualFundDetails VALUES ('AXIS',900.14);
INSERT INTO MutualFundDetails VALUES ('ZOMATO',404.14);